import Link from 'next/link';

const articles: Record<string,{tag:string;title:string;body:string[]}> = {
  'ai-agents-moving-to-action': {tag:'AI AGENTS',title:'AI agents are moving from chat to action: what businesses should prepare for',body:['AI agents are evolving from assistants that answer questions into systems that can plan, use tools and complete multi-step workflows.','For businesses, the important shift is operational: define clear tasks, permissions, human checkpoints and measurable outcomes before deploying autonomous workflows.','AgentPulse will track the products, frameworks and practical patterns that make this transition useful.']},
  'agentic-workflow-automation': {tag:'AUTOMATION',title:'The new generation of workflow automation is becoming agentic',body:['Traditional automation follows fixed rules. Agentic automation adds reasoning and adapts a workflow to changing inputs.','The strongest use cases combine deterministic steps with human approval where decisions have material business impact.','Teams should start with repetitive, measurable processes and expand only after reliability is proven.']},
  'ai-marketing-stack': {tag:'MARKETING SOFTWARE',title:'AI is reshaping the modern marketing technology stack',body:['AI is changing how teams research audiences, create content, analyze performance and manage campaigns.','The opportunity is not simply adding more AI tools. It is building a connected stack where data, workflows and measurement reinforce each other.','AgentPulse will compare the software and workflows that help modern marketing teams move faster.']}
};

export default async function Article({params}:{params:Promise<{slug:string}>}) { const {slug}=await params; const a=articles[slug] ?? articles['ai-agents-moving-to-action']; return <main className="inner-page"><header className="header"><Link className="logo" href="/">Agent<span>Pulse</span></Link><nav><Link href="/ai">AI</Link><Link href="/ai-agents">AI Agents</Link><Link href="/automation">Automation</Link><Link href="/marketing-software">Marketing Software</Link><Link href="/news">News</Link><Link href="/tools">Tools</Link><Link href="/reviews">Reviews</Link></nav><Link className="search" href="/search">⌕</Link></header><article className="article"><span className="eyebrow">{a.tag} · AGENTPULSE</span><h1>{a.title}</h1>{a.body.map(p=><p key={p}>{p}</p>)}<div className="article-actions"><Link href="/news">← More news</Link><Link href="/">Back home →</Link></div></article></main>; }
